### ISSUE TITLE
从银行取钱大于10000会多出很多

### ISSUE THREAD

**Issue by JackXu233** [HiedaCamellia/MystiasIzakaya#14]
![image](https://github.com/HiedaCamellia/MystiasIzakaya/assets/28857157/fe11ab80-5843-4912-a186-837af436c45e)
在银行中取出10000日元时会多出999张10元 大于10000日元时也会出现此情况 版本0.0.8e

**Comment by Yuqi154** [comment]
已经修复，新版本将在今天下午与其他更新内容一起推送。
你可以先使用github action的构建版本。
