### ISSUE TITLE
部分物品無法製作 & 賽錢箱崩潰

### ISSUE THREAD

**Issue by GilbertLi1206** [HiedaCamellia/MystiasIzakaya#15]
版本：1.20.1 0.0.9

目前测试无法正常制作食物：
春桩卷饼
绿野仙菇
岩浆（合成配方错误，松露變松子）

另外使用赛钱箱取出钱时会立刻造成游戏崩溃

最后关于繁中语言部份是否需要协助翻译？不然用繁中游玩时会自动试配英文

**Comment by Yuqi154** [comment]
请使用最新版本0.0.9i，如果你测试的版本为0.0.9，而且0.1.0版本正在更新中，这将是第一个稳定版本。
如果你翻译了此模组的文本，直接提交pr即可，我确实需要更多语言的翻译，非常感谢。

**Comment by GilbertLi1206** [comment]
目前因为服务器是使用MystiasIzakaya 0.0.9i-fix2，但食谱出现上述至制作BUG，因此来这里告知大佬
期待后续1.20.1稳定版本释出

**Comment by Yuqi154** [comment]
1.21与1.20.1的区别很大，模组无法兼容，我尽量在一周之内完成1.20.1版本的0.1.0内容，感谢您的关注。

**Comment by Yuqi154** [comment]
已经在1.20.1-0.1.0-rc2修复
