### ISSUE TITLE
【1.20.1】使用电话购买后无法吃喝，且购买的物品消失

### ISSUE THREAD

**Issue by Mysitia** [HiedaCamellia/MystiasIzakaya#18]
MC版本：1.20.1
模组版本：未知（根据描述来看应该是比较新的版本）
反馈来源：MCMOD评论区-46楼

问题：使用电话购买并成功扣款后无法吃喝，且打开背包后购买的物品消失。（不确定是否是购买的物品消失，还在询问）

其他信息：1.货币用的是硬币款的 2.经济方块是赛钱箱 3.在自制整合包内运行

**Comment by Mysitia** [comment]
更新：
![473d08742b39ba45cc9d74540c9862de](https://github.com/user-attachments/assets/363fb0e4-02d8-4967-82a1-7db1d32bbbcf)
![62bfcd7746e062bad07469274511b3fa](https://github.com/user-attachments/assets/bfd53fda-55fd-467c-993c-93e8283ff624)

**Comment by Yuqi154** [comment]
呃啊，最近期末可能没时间修qwq，有空看看吧xwx

**Comment by Yuqi154** [comment]
修好了awa
